name: Build CP2K images
on:
  push:
    branches:
      - master
jobs:
  build_cp2k:
    name: Build CP2K
    strategy:
      matrix:
        ver: ["v8.1.0", "v9.1.0"]
        build: ["x86-64-v3-psmp", "x86-64-psmp"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
      - name: Checkout CP2K
        uses: actions/checkout@v3
        with:
          repository: cp2k/cp2k
          ref: ${{ matrix.ver }}
          submodules: recursive
          path: cp2k
      - name: Copy the entrypoint script
        run: |
          cp scripts/prod_entrypoint.sh cp2k/tools/prod_entrypoint.sh
          sed -i '/tools\/toolchain/d' cp2k/.dockerignore
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: cp2k
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ matrix.ver }}-${{ matrix.build }}
          file: Dockerfile.${{ matrix.build }}
