name: Build CP2K images
on:
  push:
    branches:
      - master
jobs:
  build_cp2k:
    name: Build CP2K
    strategy:
      matrix:
        ver: ["v8.1.0", "v9.1.0"]
        arch: ["psmp"]
        exclude:
          - ver: "v8.1.0" # Only build cuda with 9.1
            arch: "psmp-cuda"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
      - name: Checkout CP2K
        uses: actions/checkout@v3
        with:
          repository: cp2k/cp2k
          submodules: recursive
          path: cp2k
          ref: ${{ matrix.version }}
      - name: Copy the entrypoint script
        run: cp scripts/prod_entrypoint.sh cp2k/tools/prod_entrypoint.sh
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: cp2k
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ matrix.ver }}-${{ matrix.arch }}
          file: Dockerfile.${{ matrix.arch }}
